# Generated by Django 5.2 on 2025-06-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('luogo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('tipo', models.CharField(choices=[('FESTA', 'Festa'), ('EVENTO', 'Evento'), ('ALTRO', 'Altro')], max_length=10)),
                ('coordinate', models.CharField(blank=True, help_text='Formato: latitudine, longitudine', max_length=50)),
            ],
        ),
    ]
