# Generated by Django 5.2 on 2025-07-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='coordinate',
        ),
        migrations.AddField(
            model_name='evento',
            name='latitudine',
            field=models.FloatField(default=0.0, help_text='Latitudine in gradi decimali'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='longitudine',
            field=models.FloatField(default=0.0, help_text='Longitudine in gradi decimali'),
            preserve_default=False,
        ),
    ]
