# Generated by Django 5.2 on 2025-07-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappe', '0002_remove_evento_coordinate_evento_latitudine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='immagine',
            field=models.ImageField(blank=True, help_text="Immagine dell'evento", null=True, upload_to='eventi/'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='latitudine',
            field=models.FloatField(default=0.0, help_text='Latitudine in gradi decimali'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='longitudine',
            field=models.FloatField(default=0.0, help_text='Longitudine in gradi decimali'),
        ),
    ]
