# Generated by Django 5.2 on 2025-07-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappe', '0005_eventosalvato'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='contatto',
            field=models.CharField(blank=True, help_text='Numero di telefono o email per la prenotazione', max_length=100),
        ),
        migrations.AddField(
            model_name='evento',
            name='prenotabile',
            field=models.BooleanField(default=False, help_text="L'evento è prenotabile?"),
        ),
    ]
