# Generated by Django 5.2 on 2025-07-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mappe', '0006_evento_contatto_evento_prenotabile'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mappe.evento'),
        ),
    ]
